[package]
name = "evaluator"
version = "0.1.0"
edition = "2021"

[dependencies]
ast = { path = "../ast", version = "*" }
object ={ path = "../object", version = "*" }
token ={ path = "../token", version = "*" }
parser ={ path = "../parser", version = "*" }